### ISSUE TITLE
Drag edge from both left and right

### ISSUE THREAD

**Issue by curiousily** [chthai64/SwipeRevealLayout#10]
Is it possible to have SwipeRevealLayout which can be dragged from both left and right?

**Comment by chthai64** [comment]
Currently it is not possible.

**Comment by curiousily** [comment]
Thank you for the quick response! Great job on the library, btw!

Do you have some pointers of how to implement such a functionality?

Thanks!

**Comment by chthai64** [comment]
Thanks. My goal of this library is to provide a light weight lib that can handle only one edge. Thus, I only used two layouts. Dragging edge from both left and right  will required at least 3 layouts and almost rewrite the library.

**Comment by curiousily** [comment]
Ok, I will have to search for another lib then :) Really enjoyed working with yours though :) Keep up the good work!

Thanks!
