### ISSUE TITLE
Last item of adapter XML not filling parent

### ISSUE THREAD

**Issue by tryadelion** [chthai64/SwipeRevealLayout#12]
Hello, i was testing your library to use it on an app and i found a weird bug.
this is my swipe layout test xml : 
`  
        <LinearLayout
            android:orientation="horizontal"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_marginRight="20dp">
            <Button
                android:layout_width="wrap_content"
                android:layout_height="fill_parent"
                android:text="EDIT"/>
            <Button
                android:layout_width="wrap_content"
                android:layout_height="fill_parent"
                android:text="DELETE"/>
        </LinearLayout>`
using RecyclerView.Adapter's typical implementation (https://developer.android.com/training/material/lists-cards.html) , and following your readme guide, on the last item of the adapter's dataset, the buttons show small  (wrapped around the text) and don't match or fill the parent ( i've tried both match_parent and fill_parent) , it looks like they're defaulting to wrap_content.

the rest of the interface works correctly, and the rest of items show fine, it's just the last two buttons.

**Comment by tryadelion** [comment]
more info : i gave the linearLayout i posted a background and it's filling the whole space  on every row. 
buttons still don't "fill/match" him, though. very weird.

**Comment by chthai64** [comment]
Thanks for reporting the bug. Let see if I can reproduce the bug.

**Comment by chthai64** [comment]
Can you also post your full xml layout of the row and maybe a screenshot? That may help me to work on the bug.

**Comment by tryadelion** [comment]
full xml:

http://hastebin.com/osayoqower.xml

and screenshot.

![bug](https://cloud.githubusercontent.com/assets/3778474/16032616/453964d8-3207-11e6-98f8-74f0d5f1a684.png)

**Comment by tryadelion** [comment]
for now i have forced the size to 110dp on every subview of the row LinearLayout, and that way shows correctly. so it's somewhat related to the match/fill parent on the buttons for sure. weeeird. 💯

**Comment by chthai64** [comment]
What is the color of "@color/PrimaryColor"? Is it the blue color in the screenshot? I need to make sure if the whole LinearLayout is not displayed correctly or just the buttons. Are you using version 1.2.1? I had problem with view height in the prior version 1.2.0.

**Comment by tryadelion** [comment]
yes, it 's blue.  i use compile 'com.chauthai.swipereveallayout:swipe-reveal-layout:1.2.1'

**Comment by chthai64** [comment]
I'm able to reproduce the error. When the RecyclerView is rendered, the rows which are not currently visible have incorrect children views height, which will be recycled later. That's why some random rows has the issue. I'm investigating how to fix it. The temporary fix is just set a specific size to the layout.

**Comment by chthai64** [comment]
I just uploaded version 1.2.2. Could you try the new version to see if it is fixed the issue?

**Comment by tryadelion** [comment]
i will do asap
