### ISSUE TITLE
Open the swipe during Notify

### ISSUE THREAD

**Issue by sathishsr** [chthai64/SwipeRevealLayout#13]
Hi, 
I used to update my list every half a second since I am updating data through streaming TCP connection.
During notifyDatasetChanged calling, if I try to swipe , it is giving a jerk and closes instead of opening.

**Comment by chthai64** [comment]
Thanks for reporting this. I'm investigating the issue.

**Comment by chthai64** [comment]
I haven't found a solution to the problem, so it is a limitation of this library. However, I don't think calling notifyDatasetChanged() frequently is a good idea, because it gives a jerk scrolling even for regular adapter without using the SwipeRevealLayout.
