### ISSUE TITLE
Can't drill into list item to view detail page

### ISSUE THREAD

**Issue by tejalshah84** [chthai64/SwipeRevealLayout#17]
Hi there,

Thank you for the library.

I have followed your example exactly to reveal a delete button on swipe, which works as anticipated. Except that even when the delete button is not in the foreground (i.e: it is under the main layout) and i click on that part of the foreground view, the list item gets deleted. Also, its a recycler view and I am not able to drill into the list item detail page when i click on the list item, it just deletes the item. 

I think the delete button's visibility needs to be set to gone and should be made visible onSwipe of the layout.

Please any help at your earliest convenience will be much appreciated.

**Comment by chthai64** [comment]
Hi tejalshah84,
Did you resolved the issue?
