### ISSUE TITLE
Delete one item at a time in RecyclerView

### ISSUE THREAD

**Issue by pranaypatel512** [chthai64/SwipeRevealLayout#2]
Thanks for Library.
While using RecyclerView with RecyclerView.Adapter multiple item is visible for deleting. It is good for delete multiple item at a time. See the below screenshot
https://goo.gl/OkLJrL

What if I want to allow user to delete only 1 item at a time?

**Comment by chthai64** [comment]
Thanks for the suggestion, I will implement the option to allow the user to delete one or more items at a time.

**Comment by chthai64** [comment]
Please take a look at issue 4, it's more general.
