### ISSUE TITLE
Is it possible to make setLockDrag true only for particular items of the recycler view

### ISSUE THREAD

**Issue by amarilindra** [chthai64/SwipeRevealLayout#21]
Hai 

My Recycler view contains 50 items, and I want to allow my user to swipe only particular items. 

for example, i need to disable swipe function for items at positions 10, 16, 25 but remaining positions can be swiped.

Is it possible?

**Comment by chthai64** [comment]
That will be included in the next release. #8

**Comment by amarilindra** [comment]
is this feature added ?
