### ISSUE TITLE
how to perform onItemClick in ListView?

### ISSUE THREAD

**Issue by klower1989** [chthai64/SwipeRevealLayout#22]
how to perform onItemClick in ListView

**Comment by chthai64** [comment]
#6

**Comment by klower1989** [comment]
Hi, l add setOnClickListener in my adapter for convertView, when l click this item, nothing happen, only delete view get response.the code is:
holder.delete.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(mContext, "position: " + position, Toast.LENGTH_SHORT).show();
            }
        });

        convertView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(mContext, "position: " + position, Toast
                        .LENGTH_SHORT).show();
            }
        });
and xml is:
<com.chauthai.swipereveallayout.SwipeRevealLayout
        android:id="@+id/swipe"
        android:background="#F7F4F2"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        app:dragEdge="right"
        app:mode="same_level"
        >

        <LinearLayout
            android:paddingTop="20dp"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:background="#F7F4F2">

            <ImageView
                android:id="@+id/item_write"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="15dp"
                android:src="@mipmap/community_detail_comment_btn"/>

            <ImageView
                android:id="@+id/item_praise"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="15dp"
                android:src="@mipmap/community_detail_nice_btn"/>

            <ImageView
                android:layout_marginRight="15dp"
                android:id="@+id/item_delete"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="15dp"
                android:src="@mipmap/community_detail_delete_btn"/>
        </LinearLayout>


        <LinearLayout
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/white"
            android:orientation="vertical"
            >

            <TextView
                android:layout_width="match_parent"
                android:layout_height="0.5dp"
                android:layout_marginLeft="20dp"
                android:background="@color/common_lineColor"/>

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:paddingBottom="10dp"
                android:paddingLeft="20dp"
                android:paddingRight="20dp"
                android:paddingTop="22dp">

                <ImageView
                    android:id="@+id/comment_item_praise_icon"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:src="@mipmap/community_detail_nice_icon"/>

                <TextView
                    android:id="@+id/comment_item_praise_count"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="11dp"
                    android:layout_toRightOf="@+id/comment_item_praise_icon"
                    android:text="13"
                    android:textColor="@color/common_textColor_93"
                    android:textSize="14sp"/>

                <TextView
                    android:id="@+id/comment_item_username"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_alignParentRight="true"
                    android:layout_marginLeft="11dp"
                    android:text="God Love"
                    android:textColor="@color/common_textColor_93"
                    android:textSize="14sp"/>
            </RelativeLayout>

            <TextView
                android:id="@+id/comment_item_content"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:paddingBottom="22dp"
                android:paddingLeft="20dp"
                android:paddingRight="20dp"
                android:text="contentcontentcontentcontentcontentcontent"
                android:textColor="#474747"
                android:textSize="17sp"
                />
        </LinearLayout>


    </com.chauthai.swipereveallayout.SwipeRevealLayout>
