### ISSUE TITLE
conflict with other libraries?

### ISSUE THREAD

**Issue by basmasrour** [chthai64/SwipeRevealLayout#24]
Hello..
I think there is conflict with google service and support libraries, cause when I just add dependecy of swipereveallayout and ran project it stopped with this error:
"The Google Play services resources were not found. Check your project configuration to ensure that the resources are included."

support version  23.3.0
play-services  8.4.0
what is the solustion?

**Comment by basmasrour** [comment]
![www](https://cloud.githubusercontent.com/assets/19465683/17024821/ff0a4a5e-4f61-11e6-946d-42760978cd2d.PNG)

**Comment by chthai64** [comment]
You issue seems similar to this one
http://stackoverflow.com/questions/37312340/incompatibleclasschangeerror-after-updating-to-android-build-tools-25-1-6-gcm

The solutions they got may work for you, which is updating google play service to the latest version (9.2.0) or use this:
```
compile ('com.chauthai.swipereveallayout:swipe-reveal-layout:1.4.0') {
        exclude module: 'support-v4';
}
```

**Comment by basmasrour** [comment]
Thank you very much....it's work 
thanks
