### ISSUE TITLE
rows don't adapt on rotation

### ISSUE THREAD

**Issue by marconealberto** [chthai64/SwipeRevealLayout#25]
how can I have the rows to readapt to the new width on rotation? I would like to avoid to handle the rotation event and redraw the whole list.
Is there a way?

thank you

**Comment by chthai64** [comment]
It's the way Android works and it's a recommended way, the activity will be destroyed and re-create when the orientation is changed. So to handle the orientation change, you should use `viewBinderHelper.saveStates()` and  `viewBinderHelper.restoreStates() `like in the instruction that I wrote in the README file.

You can try to use the trick in https://developer.android.com/guide/topics/resources/runtime-changes.html to avoid activity restart, but it may not work correctly. They also said that 

> This technique should be considered a last resort when you must avoid restarts due to a configuration change and is not recommended for most applications.

**Comment by marconealberto** [comment]
thank you for the clarification. Problem is that I use a Drawer and most of the views in my app are fragments. I would have to manage case by case and it's too much of an hassle.  Thank you anyways

**Comment by JyotiDubey** [comment]
Any update on this issue? I am using the swipe reveal layout inside a fragment. when the screen is rotated the list items are not retaining the "match_parent" for the width.
