### ISSUE TITLE
setOpenOnlyOne does not work

### ISSUE THREAD

**Issue by Draffodx** [chthai64/SwipeRevealLayout#27]
I am using version 1.4.0 on Android 6.0.1 and the setOpenOnlyOne option doesn't seem to work.

I use Gradle to get the library as follows:

> compile 'com.chauthai.swipereveallayout:swipe-reveal-layout:1.4.0'

Then in my view holder I create the binderhelper and set the setOpenOnlyOne option as follows:

```
private final ViewBinderHelper viewBinderHelper;
viewBinderHelper = new ViewBinderHelper();
viewBinderHelper.setOpenOnlyOne(true);
```

I am using a RecyclerView and I can still slide all of the views open.

However

**Comment by imneeraj** [comment]
hi. did you find the solution of this question?

**Comment by yalematta** [comment]
I have the same issue. How have you fixed that?

**Comment by miladcoder** [comment]
is not work for first run . 
when activity started and fill listview . this option not work. but when scrolling listview and stop tha's work . this is bug . how can handle ?
