### ISSUE TITLE
onItemClick in ListView not working...

### ISSUE THREAD

**Issue by zhockz** [chthai64/SwipeRevealLayout#32]
regarding on #6 , still i cannot make it work pls. help... specially the last part that you mentioned...
"use adapter.setOnItemClickListener() before attaching it to the listview"... sorry i just new on android development.. thanks :)

**Comment by chthai64** [comment]
Can you send me your code relates to the issue?

**Comment by zhockz** [comment]
hi this is my listview content
`<?xml version="1.0" encoding="utf-8"?>
<com.chauthai.swipereveallayout.SwipeRevealLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:padding="0dp"
    xmlns:tools="http://schemas.android.com/tools"
    android:descendantFocusability="blocksDescendants">

    <RelativeLayout
        android:id="@+id/leftOption"
        android:layout_width="285dp"
        android:layout_height="wrap_content"
        android:padding="15dp"
        android:layout_margin="0dp"
        android:background="@color/colorLightGray"
        app:dragEdge="left">

        <Button
            android:id="@+id/addToCart"
            android:layout_width="60dp"
            android:layout_height="50dp"
            android:background="@drawable/add_cart_gray"
            android:layout_centerVertical="true"/>

        <Button
            android:id="@+id/wishList"
            android:layout_width="60dp"
            android:layout_height="50dp"
            android:background="@drawable/wishlist1"
            android:layout_toRightOf="@+id/addToCart"
            android:layout_centerVertical="true"/>

    </RelativeLayout>



    <RelativeLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="#ffffff"
        android:padding="15dp">

    <ImageView
        android:id="@+id/prodImage"
        android:layout_width="60dp"
        android:layout_height="60dp"
        android:paddingRight="15dp"
        android:src="@drawable/logo"
        android:layout_centerVertical="true"/>

    <RelativeLayout
        android:id="@+id/col1"
        android:layout_width="170dp"
        android:layout_height="match_parent"
        android:layout_toRightOf="@id/prodImage">

        <TextView
            android:id="@+id/prodName"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:text="Description"
            android:gravity="top"
            android:textSize="15sp"
            android:textStyle="bold"
            android:textColor="@color/colorDarkGray" />

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_below="@id/prodName">

            <TextView
                android:id="@+id/qtyLabel"
                android:layout_width="35dp"
                android:layout_height="wrap_content"
                android:text="QTY:"
                android:padding="0dp"
                android:layout_margin="0dp"
                android:textSize="15sp"
                android:gravity="left"
                android:textColor="@color/colorLightGray"/>
            <TextView
                android:id="@+id/qty"
                android:layout_width="40dp"
                android:layout_height="wrap_content"
                android:text="1"
                android:padding="0dp"
                android:layout_margin="0dp"
                android:textSize="15sp"
                android:gravity="left"
                android:textColor="@color/colorLightGray"
                android:layout_toRightOf="@+id/qtyLabel"/>

            <TextView
                android:id="@+id/prodSize"
                android:layout_width="50dp"
                android:layout_height="wrap_content"
                android:text="Description"
                android:padding="0dp"
                android:layout_margin="0dp"
                android:textSize="15sp"
                android:gravity="left"
                android:textColor="@color/colorLightGray"
                android:layout_toRightOf="@+id/qty"/>

            <ImageView
                android:id="@+id/prodMLogo"
                android:layout_width="60dp"
                android:layout_height="match_parent"
                android:src="@drawable/logo"
                android:paddingLeft="5dp"
                android:layout_toRightOf="@+id/prodSize"/>

        </RelativeLayout>

    </RelativeLayout>

    <RelativeLayout
        android:layout_width="100dp"
        android:layout_height="match_parent"
        android:layout_toRightOf="@id/col1"
        android:gravity="right"
        android:paddingRight="10dp">

        <TextView
            android:id="@+id/sr"
            android:layout_width="25dp"
            android:layout_height="match_parent"
            android:text="SR"
            android:padding="0dp"
            android:textSize="15sp"
            android:layout_margin="0dp"
            android:textColor="@color/colorDarkGray"
            android:layout_centerVertical="true" />
        <TextView
            android:id="@+id/prodPrice"
            android:layout_width="50dp"
            android:layout_height="match_parent"
            android:text="Description"
            android:layout_margin="0dp"
            android:padding="0dp"
            android:textSize="20sp"
            android:textColor="@color/colorDarkGray"
            android:layout_centerVertical="true"
            android:layout_toRightOf="@id/sr"/>
    </RelativeLayout>


    <TextView
        android:id="@+id/prodNameAr"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:text="Description"
        android:textSize="20sp"
        android:gravity="center_vertical|left"
        android:textColor="@color/colorDarkGray"
        android:layout_centerVertical="true"
        android:visibility="invisible"/>

    <TextView
        android:id="@+id/prodQuantity"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:text="Description"
        android:textSize="20sp"
        android:gravity="center_vertical|left"
        android:textColor="@color/colorDarkGray"
        android:layout_centerVertical="true"
        android:visibility="invisible"/>



    <TextView
        android:id="@+id/prodSize"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:text="Description"
        android:textSize="20sp"
        android:gravity="center_vertical|left"
        android:textColor="@color/colorDarkGray"
        android:layout_centerVertical="true"
        android:visibility="invisible"/>

    <TextView
        android:id="@+id/prodId"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:text="Product Id"
        android:visibility="invisible"/>
    </RelativeLayout>

    

</com.chauthai.swipereveallayout.SwipeRevealLayout>`

and this my adapter
`public class ProductListAdapter extends BaseAdapter{
    private Context prodcontext;
    private List<ProductList> prodList;
    public static final String IMAGE_BASEURL = "http://abuoffer.s3.amazonaws.com/";
    private LruCache<Integer,Bitmap> imageCache;
    private LayoutInflater inflater = null;
    private RequestQueue queue;
    private AdapterView.OnItemClickListener onItemClickListener;
    ImageView addToCart;


    public ProductListAdapter(Context prodcontext, List<ProductList> list) {


        this.prodcontext = prodcontext;
        this.prodList = list;
        inflater = LayoutInflater.from(prodcontext);

        final int maxMemory = (int) (Runtime.getRuntime().maxMemory() / 1024);
        final int cacheSize = maxMemory / 8;
        imageCache = new LruCache<>(cacheSize);


        queue = Volley.newRequestQueue(prodcontext);
    }

    public class ViewHolder {

        TextView _id;
        TextView _name;
        TextView _nameAr;
        ImageView _image;
        ImageView _logo;
        TextView _slug;
        TextView _quantity;
        TextView _price;
        TextView _size;

    }

    @Override
    public int getCount() {
        return prodList.size();
    }

    @Override
    public Object getItem(int position) {
        return prodList.get(position);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public View getView(final int position, View convertView, final ViewGroup parent) {

        final View view = convertView;
        final ProductList productList = prodList.get(position);
        final ViewHolder holder;

        if(convertView == null) {

            convertView = inflater.inflate(R.layout.product_list,null);
            holder = new ViewHolder();

            holder._id = (TextView) convertView.findViewById(R.id.prodId);
            holder._name = (TextView) convertView.findViewById(R.id.prodName);
            holder._nameAr = (TextView) convertView.findViewById(R.id.prodNameAr);
            holder._image = (ImageView) convertView.findViewById(R.id.prodImage);
           holder._logo = (ImageView) convertView.findViewById(R.id.prodMLogo);
            holder._quantity = (TextView) convertView.findViewById(R.id.prodQuantity);
            holder._price = (TextView) convertView.findViewById(R.id.prodPrice);
            holder._size = (TextView) convertView.findViewById(R.id.prodSize);

            convertView.setTag(holder);
        }
        else {

            holder = (ViewHolder) convertView.getTag();
        }

        holder._id.setText(productList.getPid().toString());
        holder._name.setText(productList.getPname().toString());
        holder._nameAr.setText(productList.getPnameAr().toString());
        holder._quantity.setText(productList.getPquantity().toString());
        holder._price.setText(productList.getPprice().toString());
        holder._size.setText(productList.getPsize().toString());

        Bitmap bitmap = imageCache.get(Integer.parseInt(productList.getPid()));
        holder._image = (ImageView) convertView.findViewById(R.id.prodImage);
       holder._logo = (ImageView) convertView.findViewById(R.id.prodMLogo);

        if (bitmap != null) {

            holder._image.setImageBitmap(bitmap);
            holder._logo.setImageBitmap(bitmap);

        }else {

            String imageURL = IMAGE_BASEURL+productList.getPimage();
            ImageRequest request = new ImageRequest(imageURL,
                    new Response.Listener<Bitmap>() {
                        @Override
                        public void onResponse(Bitmap response) {

                            holder._image.setImageBitmap(response);
                            imageCache.put(Integer.parseInt(productList.getPid()), response);

                        }
                    },
                    90, 90,
                    Bitmap.Config.ARGB_8888,
                    new Response.ErrorListener() {
                        @Override
                        public void onErrorResponse(VolleyError error) {

                            Log.d("error",error.getMessage().toString());
                        }
                    });
            queue.add(request);

            String logoUrl = IMAGE_BASEURL+"markets_logos/"+productList.getMlogo();
            ImageRequest request1 = new ImageRequest(logoUrl,
                    new Response.Listener<Bitmap>() {
                        @Override
                        public void onResponse(Bitmap response) {

                            holder._logo.setImageBitmap(response);
                            imageCache.put(Integer.parseInt(productList.getPid()), response);

                        }
                    },
                    90, 90,
                    Bitmap.Config.ARGB_8888,
                    new Response.ErrorListener() {
                        @Override
                        public void onErrorResponse(VolleyError error) {

                            Log.d("error",error.getMessage().toString());
                        }
                    });


            queue.add(request1);


        }

        convertView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (onItemClickListener != null) {
                    onItemClickListener.onItemClick(null, view, position, -1);
                }
            }
        });


        return convertView;
    }

    public void setOnItemClickListener(AdapterView.OnItemClickListener onItemClickListener) {
        this.onItemClickListener = onItemClickListener;
    }
}`

this is my main activity/fragment
`public class ProductsActivity extends Fragment{

    DrawerLayout productDrawerLayout;
    List<ProductCategory> productCategoryList;
    List<ProductSubCategory> productSubCategoryList;
    List<ProductList> productLists;
    ListView lv;
    ListView subLv;
    ListView prodLv;
    String catId;
    String catName;
    String uri = "http://stag.abuoffer.com/android2/category.php";
    String uriSub;
    String uriProd;
    Toolbar toolbar;
    NavigationView subCatDrawer;
    String catSubId;
    TextView topToolbarTitle;
    Button topToolbarBackButtonCloseDrawer;
    private ProgressBar spinner;
    private static int splashInterval = 3000;
    Button addTocart;




    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        View view = inflater.inflate(R.layout.product_activity, container, false);
        setHasOptionsMenu(true);

        spinner = (ProgressBar) view.findViewById(R.id.progressBar1);
        toolbar = (Toolbar) view.findViewById(R.id.topToolbar);
        productDrawerLayout = (DrawerLayout) view.findViewById(R.id.productSubMenu);
        productDrawerLayout.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);
        lv = (ListView) view.findViewById(R.id.productsCategory);
        subLv = (ListView) view.findViewById(R.id.productSubCategory);
        prodLv = (ListView) view.findViewById(R.id.productList);
        subCatDrawer = (NavigationView) view.findViewById(R.id.subCatDrawer);
        topToolbarTitle = (TextView) view.findViewById(R.id.topToolbarTitle);
        addTocart = (Button) view.findViewById(R.id.addToCart);


        requestData(uri);


        /*
        new Handler().postDelayed(new Runnable() {

            @Override
            public void run() {

                spinner.setVisibility(View.GONE);

                lv.setVisibility(View.VISIBLE);
            }

            private void finish() {
                // TODO Auto-generated method stub

            }
        }, splashInterval);
        */
        ((MainActivity) getActivity()).changeToolBarBackbutton();
        topToolbarBackButtonCloseDrawer = (Button) ((MainActivity) getActivity()).findViewById(R.id.topToolbarBackButtonCloseDrawer);

        topToolbarBackButtonCloseDrawer.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                productDrawerLayout.closeDrawers();
                topToolbarBackButtonCloseDrawer.setVisibility(View.GONE);
            }
        });

        lv.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                catId = ((TextView) view.findViewById(R.id.categoryId)).getText().toString();
                catName = ((TextView) view.findViewById(R.id.catName)).getText().toString();
                productDrawerLayout.openDrawer(Gravity.END);
                uriSub = "http://stag.abuoffer.com/android2/sub_category.php?cat_id="+catId;
                requestDataSub(uriSub);

                ((MainActivity) getActivity()).changeToolBarText("Sub Category");
                topToolbarBackButtonCloseDrawer.setVisibility(View.VISIBLE);
            }
        });

        subLv.setOnItemClickListener(new AdapterView.OnItemClickListener(){
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                catSubId = ((TextView) view.findViewById(R.id.prodSubItemId)).getText().toString();
                productDrawerLayout.closeDrawer(Gravity.END);
                productDrawerLayout.openDrawer(Gravity.START);
                uriProd = "http://stag.abuoffer.com/android2/product_by_subcategory.php?subcat_id="+catSubId;
                requestDataProd(uriProd);

                ((MainActivity) getActivity()).changeToolBarText("Products");
                topToolbarBackButtonCloseDrawer.setVisibility(View.VISIBLE);
            }
        });


        prodLv.setOnItemClickListener(new AdapterView.OnItemClickListener(){
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Toast.makeText(getContext(), "Position "+position, Toast.LENGTH_SHORT).show();
            }

        });









        if(productDrawerLayout.isDrawerOpen(GravityCompat.START)) {
            topToolbarBackButtonCloseDrawer.setVisibility(View.VISIBLE);
        }

        return view;
    }

    public void requestData(String uri) {
        StringRequest request = new StringRequest(uri,
                new Response.Listener<String>() {
                    @Override
                    public void onResponse(String response) {
                        productCategoryList = ProductCategoryParser.parseData(response);
                        ProductCategoryAdapter adapter = new ProductCategoryAdapter(getActivity(), productCategoryList);
                        lv.setAdapter(adapter);
                    }
            },
                new Response.ErrorListener() {
                    @Override
                    public void onErrorResponse(VolleyError error) {
                        Toast.makeText(getActivity(), error.getMessage().toString(), Toast.LENGTH_SHORT).show();
                    }
             });

            RequestQueue queue = Volley.newRequestQueue(getActivity());
            queue.add(request);

    }


    public void requestDataSub(String uriSub){
        StringRequest request = new StringRequest(uriSub,
                new Response.Listener<String>() {
                    @Override
                    public void onResponse(String response) {
                        productSubCategoryList = ProductSubCategoryParser.parseData(response);
                        ProductSubCategoryAdapter subAdapter = new ProductSubCategoryAdapter(getActivity(), productSubCategoryList);
                        subLv.setAdapter(subAdapter);
                    }
                },
                new Response.ErrorListener() {
                    @Override
                    public void onErrorResponse(VolleyError error) {
                        Toast.makeText(getActivity(), error.getMessage().toString(), Toast.LENGTH_SHORT).show();
                    }
                });

        RequestQueue queue = Volley.newRequestQueue(getActivity());
        queue.add(request);
    }

    public void requestDataProd(String uriProd){
        StringRequest request = new StringRequest(uriProd,
                new Response.Listener<String>() {
                    @Override
                    public void onResponse(String response) {
                        productLists = ProductListParser.parseData(response);
                        ProductListAdapter prodAdapter = new ProductListAdapter(getActivity(), productLists);
                        prodLv.setAdapter(prodAdapter);
                    }
                },
                new Response.ErrorListener() {
                    @Override
                    public void onErrorResponse(VolleyError error) {
                        Toast.makeText(getActivity(), error.getMessage().toString(), Toast.LENGTH_SHORT).show();
                    }
                });

        RequestQueue queue = Volley.newRequestQueue(getActivity());
        queue.add(request);
    }

    /*
    Toast.makeText(getContext(),
    "asdasdas",
    Toast.LENGTH_LONG).show();
    return true;
    */
    @Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);
        if (isVisibleToUser) {
            if(productDrawerLayout.isDrawerOpen(GravityCompat.START) || productDrawerLayout.isDrawerOpen(GravityCompat.END)) {
                topToolbarBackButtonCloseDrawer.setVisibility(View.VISIBLE);
            }
        }
    }
}`

**Comment by hamid36165** [comment]
i am also facing th same problem. please help me

**Comment by lxpeng** [comment]
me tooo

**Comment by curry-zhou** [comment]
me too,,,,,,

**Comment by MatthewDong** [comment]
same issue

**Comment by Cybrosys** [comment]
Same.

**Comment by MaksimVialykh** [comment]
I found this issue on Samsung S7.

To solve it I handle swipe result 

swipeRevealLayout.setSwipeListener(new SwipeRevealLayout.SwipeListener() {
				@Override
				public void onClosed(SwipeRevealLayout view) {
					Log.d(getClass().toString(), "onClosed");
					if (!wasOpen) {
						content.callOnClick();
					}
					wasOpen = false;
				}

				@Override
				public void onOpened(SwipeRevealLayout view) {
					Log.d(getClass().toString(), "onOpened");
					wasOpen = true;
				}

				@Override
				public void onSlide(SwipeRevealLayout view, float slideOffset) {
					Log.d(getClass().toString(), "onSlide: " + slideOffset);
					if (slideOffset > 0.01) {
						wasOpen = true;
					}
				}
			});

**Comment by yalematta** [comment]
@MaksimVialykh this hack is not very efficient. Closing when it's not open doesn't really work every time you "click" on your item.

**Comment by tyn17** [comment]
This work for me with setOnClickListener to "cell_data_layout" stead of ConvertView

`<com.chauthai.swipereveallayout.SwipeRevealLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/swipe_layout"
    android:layout_width="match_parent"
    android:layout_height="wrap_content" android:paddingBottom="4dp"
    app:dragEdge="right" app:mode="same_level" android:clickable="true" android:descendantFocusability="blocksDescendants">
<LinearLayout  android:id="@+id/cell_action_layout"
            android:layout_width="wrap_content"
            android:layout_height="@dimen/history_row_height" android:orientation="horizontal">
...
</LinearLayout>

        <RelativeLayout android:id="@+id/cell_data_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">
...
</RelativeLayout>
</com.chauthai.swipereveallayout.SwipeRevealLayout>`

**Adapter**
```
convertView = inflater.inflate(R.layout.list_swipe_item, parent, false);
            viewHolder.mCellDataLayout = (RelativeLayout) convertView.findViewById(R.id.cell_data_layout);
viewHolder.mCellDataLayout.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(mContext, "Clicked", Toast.LENGTH_SHORT).show();
                if (mOnItemClickListener != null) {
                    mOnItemClickListener.onItemClick(null, view, position, -1);
                }
            }
        });
```
