### ISSUE TITLE
Open One at a time

### ISSUE THREAD

**Issue by sathishsr** [chthai64/SwipeRevealLayout#4]
Is it possible to open only one at a  time? Eg.  if row 1is opened and I now opens row two means , row one should automatically close.

**Comment by chthai64** [comment]
Currently it's not possible. I will add this feature in the next version

**Comment by Mokshi1709** [comment]
Is it possible to use both left and right swipe within single item like gmail app?

**Comment by chthai64** [comment]
For now it's also not possible. Currently I only use two layouts, but using both sides will required 3 layouts and significant code changes. I will consider implementing that feature if I can make it not too complicated.

**Comment by chthai64** [comment]
I implemented the open-one-at-a-time feature. It was released under version 1.1.0.
