### ISSUE TITLE
programmatically open a row?

### ISSUE THREAD

**Issue by marconealberto** [chthai64/SwipeRevealLayout#5]
I don't see any methods to do that, is it possible to programmatically open a row from the adapter?

**Comment by chthai64** [comment]
Currently there is no direct way to do it. I will add this feature in the next version.

**Comment by marconealberto** [comment]
this would be a really cool feature, right now our app design requires something like that..

**Comment by chthai64** [comment]
This can be easily done in ViewBinderHelper class. Does it help if I add a method called ```openRow(String id)```, which ```id``` is the unique id that identifies the data object?

**Comment by marconealberto** [comment]
that would be exactly what I was thinking about.

**Comment by chthai64** [comment]
Check out the new version. I've implemented ```viewBinderHelper.openLayout(String id)``` and ```viewBinderHelper.closeLayout(String id)```.

**Comment by marconealberto** [comment]
I'm trying it but I don't understand what id I'm supposed to put in.
I tried this inside the adapter:

```
holder.plusBtn.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                        binderHelper.openLayout(""+v.getId());
                }
            });
```

but it doesn't work.

**Comment by marconealberto** [comment]
I tried the convertView.getId(), the item.getId() ... but apparently nothing happens. Wouldn't it better to pass the index of the row? so it's kind of standard

**Comment by chthai64** [comment]
It's the same id when you use viewBinderHelper.bind(String id).  It's the unique id which identifies the data object that you binds to the view. ViewBinderHelper doesn't store row index, because it may change when the user removes or adds new row. You can implement open/close row position like this:
```java
    public void removeRow(int position) {
        if (dataSet != null && 0 <= position && position < dataSet.size()) {
              YourDataObject dataObject = dataSet.get(position);
               viewBinderHelper.openLayout(dataObject.getId());
        }
}
```

It's up to you to define the id of the dataObject.

**Comment by marconealberto** [comment]
great stuff! thanks for your quick response!
