### ISSUE TITLE
How can i set drag sensitivity for swipe layout

### ISSUE THREAD

**Issue by tanakasama** [chthai64/SwipeRevealLayout#51]
How can i set drag sensitivity for swipe layout ? In the some devices (as Sony Xperia Z4), too difficult to click children in swipe layout.

I did try this:
mDragHelper = ViewDragHelper.create(this, 1.0f, mDragHelperCallback);
==> mDragHelper = ViewDragHelper.create(this, 0.1f, mDragHelperCallback);
But it still too sensitivity, so difficult to click to children view.

Thanks in advanced.

**Comment by KishorAndroid** [comment]
Check onViewPositionChanged(...)
....
boolean isMoved = (mMainView.getLeft() != mLastMainLeft) || (mMainView.getTop() != mLastMainTop);
....
and
ViewCompat.postInvalidateOnAnimation(SwipeRevealLayout.this);

try experimenting with these values.

**Comment by KishorAndroid** [comment]
OR

private static final int DEFAULT_MIN_FLING_VELOCITY = 300; // dp per second
    private static final int DEFAULT_MIN_DIST_REQUEST_DISALLOW_PARENT = 1; // dp

**Comment by tanakasama** [comment]
I did try both of these method. But it still to sensitivity. Anyone have a solutions for this issue ?

Thanks in advanced.

**Comment by tanakasama** [comment]
I did resolved this buy other way. And its work good !. Close this issue.

**Comment by jitendraAndroid** [comment]
@tanakasama Can you please reply how you solved this issue.
