### ISSUE TITLE
Swipe one view at one time

### ISSUE THREAD

**Issue by cresttechnosoft** [chthai64/SwipeRevealLayout#59]
Hello 

I have checked your library, it is cool library. Your library allow me to swipe multiple list items to delete. But I want to open one row at one time. e.g. I have opened my listview's item no. 2, now if I open other item then the previous row should be closed. 
Please let me know. How can I do it with your library.
Thanks

**Comment by cresttechnosoft** [comment]
Hi 
Please reply

**Comment by pj210493** [comment]
This will work for you-
binderHelper.setOpenOnlyOne(true);

**Comment by Krishna25Vrinsoft** [comment]
It's not working for me. In which method I need to put?

**Comment by pj210493** [comment]
@Krishna25Vrinsoft In the constructor of your adapter.

**Comment by sanamdongol** [comment]
@Krishna25Vrinsoft use Recyclerview to make it work. I've used Recyclerview and its working but don't forget to use 
binderHelper.setOpenOnlyOne(true);
 in your constructor of your adapter

**Comment by ashishCDN0135** [comment]
viewBinderHelper.bind(holder.swipeRevealLayout, dataObject.getId());

this should be a unique id dataObject.getId(),if u want to show swipe view one at time.
make my day, thanks..

**Comment by hhirpara26** [comment]
**@pj210493**  Thanks a lot. it's working
