### ISSUE TITLE
How to set OnClickListener for whole SwipeRevealLayout ?

### ISSUE THREAD

**Issue by JoeShiguang** [chthai64/SwipeRevealLayout#7]
Hi,
I wanna set a clickListener for the swipeRevealLayout, 
and when the swipeRevealLayout is closed and click it, call the clickListener.
Any suggestions ?  :)

**Comment by marconealberto** [comment]
The developer replied to a similar question [here](https://github.com/chthai64/SwipeRevealLayout/issues/6#issuecomment-219076391)

**Comment by JoeShiguang** [comment]
Thanks for your reply.
But it not work for me and i use it with RecyclerView. T_T
Here's my code:
![activity](https://cloud.githubusercontent.com/assets/16753307/15354968/d120b9fa-1d22-11e6-877f-609c3cab67ad.png)
![adapter](https://cloud.githubusercontent.com/assets/16753307/15354967/d12092d6-1d22-11e6-9ebc-148f20e04836.png)

**Comment by chthai64** [comment]
Hi JoeShiguang ,

What is type of view holder.root? You can set onClick for main layout and secondary layout, but you can't set onClick for the whole swipeRevealLayout. 

I think you can achieve the same effect you want by setting onClick for the mainLayout, then you can able to click it after the swipeLayout is closed.

Also, you shouldn't use ```position``` variable directly, use ```holder.getAdapterPosition()``` instead. To make sure the mainLayout is really clickable, you can try to use ```android:clickable="true"``` for the mainLayout.

**Comment by JoeShiguang** [comment]
Thanks for your help.  It work now.   :)
