### ISSUE TITLE
lock swipe just for some rows?

### ISSUE THREAD

**Issue by marconealberto** [chthai64/SwipeRevealLayout#8]
I looked into the documentation but I haven't found much.

I tried to set an empty SwipeListener and I looked if there was a "null" value for the dragEdge property. None of the solutions above worked.

**Comment by chthai64** [comment]
If they are in the RecyclerView or ListView, currently there is no direct way to do it. I can modify the ```ViewBinderHelper``` class again to add this new feature.

**Comment by chthai64** [comment]
Implemented.
