### ISSUE TITLE
match_parent is not working for menu items

### ISSUE THREAD

**Issue by nzackoya** [chthai64/SwipeRevealLayout#9]

**Comment by chthai64** [comment]
Please give me more detail on this issue.

**Comment by nzackoya** [comment]
Here is my xml part
<com.chauthai.swipereveallayout.SwipeRevealLayout
        android:id="@+id/swipe_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:mode="normal"
        app:dragEdge="right">
    <TextView 
              android:layout_height="match_parent"
              android:layout_width="100dp"
              android:gravity="center"
              android:drawableTop="@drawable/dots"
              android:text="@string/report"
              android:textColor="@android:color/white"
              android:background="@android:color/holo_red_dark"
    />
<RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
...
in the RelativeLayout I have image view which can have different height depending on picture I set there. So, everything works fine except that TextView which has just height that equals to text height, but it should be same height as the image has. It seems to me that SwipeRevealLayout doesn't have height at all or it is not measuring itself in a right way. Please help me to get around this issue.

**Comment by chthai64** [comment]
Can you take a screenshot of the UI? I haven't try the layout on menu items yet. The way height works is:
if one of the layout uses ```match_parent```, then SwipeLayout just uses the largest height value it can. Otherwise, it uses the max value of main layout and secondary layout.

**Comment by nzackoya** [comment]
![screenshot_20160525-172847](https://cloud.githubusercontent.com/assets/4866869/15543778/e034be06-229e-11e6-8a05-e1dc4dfe912d.png)

**Comment by nzackoya** [comment]
see the report button is not is not filling the entire space, but it should. The images has different heights, that's why I need to set wrap_content to SwipeRevealLayout.

**Comment by chthai64** [comment]
I'm able reproduce the error. I'm working to resolve it. Somehow it only affects when the layout is used in list.

**Comment by chthai64** [comment]
I just uploaded a new version with the fix. Can you try ```compile 'com.chauthai.swipereveallayout:swipe-reveal-layout:1.2.1'``` and see if it is fixed?
